export interface RenderCard {
  id: string;
  title: string;
  status: string;
  requirements: string[];
  grandfathered_requirements: string[];
  dependencies: string[];
  priority: number;
  blocked: { reason: string } | null;
  workflow: {
    design: { pr: { url: string } | null };
    split_decision: { override: { decision: string } | null };
    implementation: Record<string, unknown>;
    review: Record<string, unknown>;
    ship: { product_pr: { url: string } | null };
  };
}

const SECTIONS: readonly [string, string][] = [
  ["Blocked", "blocked"],
  ["Backlog", "backlog"],
  ["Designing", "designing"],
  ["Design review", "design_review"],
  ["Ready for implementation", "ready_for_implementation"],
  ["Implementing", "implementing"],
  ["Implementation review", "implementation_review"],
  ["Ready to ship", "ready_to_ship"],
  ["Shipping", "shipping"],
  ["Done", "done"],
  ["Replaced", "replaced"],
];

const escapeInline = (value: string): string =>
  value.replace(/[\\`*_\[\]<>#\r\n]/g, (character) => `\\${character}`);

function cardBullet(card: RenderCard): string {
  const requirements = card.requirements.length === 0 ? "none" : card.requirements.join(", ");
  const dependencies = card.dependencies.length === 0 ? "none" : card.dependencies.join(", ");
  let line = `- [${escapeInline(card.id)}](./${encodeURIComponent(card.id)}.md) — ${escapeInline(card.title)} · priority ${card.priority} · requirements ${requirements} · dependencies ${dependencies}`;
  if (card.grandfathered_requirements.length > 0) {
    line += ` · grandfathered: ${card.grandfathered_requirements.join(", ")}`;
  }
  if (card.workflow.split_decision.override?.decision === "proceed_unsplit") {
    line += " · split override: proceed unsplit";
  }
  if (card.blocked) {
    line += ` · status: ${card.status} · blocked: ${escapeInline(card.blocked.reason)}`;
  } else if (card.workflow.design.pr) {
    line += ` · design PR: ${escapeInline(card.workflow.design.pr.url)}`;
  } else if (card.workflow.ship.product_pr) {
    line += ` · product PR: ${escapeInline(card.workflow.ship.product_pr.url)}`;
  }
  return line;
}

/** Render the committed dashboard from a validated, immutable card snapshot. */
export function renderBoard(cards: readonly RenderCard[]): string {
  const sorted = [...cards].sort((left, right) => left.priority - right.priority || left.id.localeCompare(right.id));
  const lines = [
    "# Kanban board",
    "",
    "> Generated by pi-kanban-flow from validated card records. Do not edit manually.",
    "",
  ];
  for (const [heading, status] of SECTIONS) {
    lines.push(`## ${heading}`, "");
    const sectionCards = sorted.filter((card) => (card.blocked ? status === "blocked" : card.status === status));
    lines.push(...sectionCards.map(cardBullet));
    lines.push("");
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
