import assert from "node:assert/strict";
import { test } from "node:test";
import { executeParallelStrict, type DispatchPlan, type DispatchSuccess, type StrictDispatchTask } from "../../extensions/kanban-flow/agents/runner.ts";
import { policyForAgent } from "../../extensions/kanban-flow/agents/policy.ts";
const run = "KFRUN-20260115T103000000Z-abcdefgh";
function task(index: number, name: "requirements-checker" | "reviewer" = "requirements-checker"): StrictDispatchTask { const policy = policyForAgent(name); return { plan: { dispatchId: run, agent: {} as any, model: {} as any, policy, executable: "", argv: [], redactedArgv: [], environment: process.env, cwd: "", promptPath: "", taskEnvelope: "", cleanup: async () => {} } as DispatchPlan, expectation: { role: policy.resultRole, tool: policy.resultTool, dispatchId: run, cardId: "none" } }; }
function success(index: number): DispatchSuccess { return { runtime: { payload: {} as any, provider: "p", model: "m", thinking: "high", stopReason: "toolUse", usage: { input: index + 1 }, eventCount: 1 }, exitCode: 0, stderr: "", startedAt: "", completedAt: "" }; }
test("strict parallel dispatch caps concurrency and preserves configured order", async () => { let active = 0; let peak = 0; const tasks = [0,1,2,3].map((i) => task(i)); const result = await executeParallelStrict(tasks, 2, undefined, async (plan) => { const index = tasks.findIndex((entry) => entry.plan === plan); active++; peak = Math.max(peak, active); await new Promise((resolve) => setTimeout(resolve, (4-index)*5)); active--; return success(index); }); assert.equal(peak, 2); assert.deepEqual(result.outcomes.map((outcome) => outcome.index), [0,1,2,3]); assert.deepEqual(result.outcomes.map((outcome) => outcome.state), ["completed","completed","completed","completed"]); assert.equal(result.usage.input, 10); });
test("terminal failure stops queued launches and reports independent outcomes", async () => { const tasks = [0,1,2,3].map((i) => task(i)); const launched: number[] = []; const result = await executeParallelStrict(tasks, 2, undefined, async (plan, _expectation, signal) => { const index = tasks.findIndex((entry) => entry.plan === plan); launched.push(index); if (index === 0) throw new Error("bad stream"); await new Promise((resolve, reject) => { const timer = setTimeout(resolve, 50); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(new Error("aborted peer")); }, { once: true }); }); return success(index); }); assert.equal(result.ok, false); assert.deepEqual(launched.sort(), [0,1]); assert.deepEqual(result.outcomes.map((outcome) => outcome.state), ["failed","failed","skipped","skipped"]); });
test("producers and broad policies cannot enter parallel runner", async () => { await assert.rejects(executeParallelStrict([{ ...task(0), plan: { ...task(0).plan, policy: policyForAgent("requirements-producer") } }], 1), /Only independent strict/); });
