import assert from "node:assert/strict";
import { test } from "node:test";
import type { BoardSnapshot } from "../../extensions/kanban-flow/board/repository.ts";
import { RequirementsApprovalRequest, assertApprovalFresh, prepareRequirementsApproval } from "../../extensions/kanban-flow/requirements/approval.ts";
import { createPiApprovalAdapter } from "../../extensions/kanban-flow/tools/requirements.ts";

const base = "a".repeat(40);
const config = { repository: { forge: "github", gh_command: "gh", remote: "origin", base_branch: "main" }, state_prs: { merge_policy: "human" }, lock: { ttl_seconds: 1800, heartbeat_seconds: 30 }, scheduler: { wip_limit: 1, priority_order: "ascending" }, rework: { design_limit: 2, implementation_limit: 2 }, review: { lenses: ["acceptance"], max_parallel: 1 }, project_commands: { test: ["npm", "test"] }, agent_models: { default: "inherit", overrides: {} }, agents: { allow_project_overrides: true, report_overrides: true }, resources: { broad_policy_allowed_skills: [] } } as any;
function snapshot(): BoardSnapshot { return { root: "/workspace/repo", board: { harness: "pi", board_schema_version: 1, last_writer_package_version: "1.0.0", project: { repository_id: "owner/repo" }, ids: { next_requirement: 1, next_card: 1, next_acceptance_criterion: 1, next_finding: 1 }, state: { last_reconciled_at: "2026-01-01T00:00:00Z", last_state_transaction: null }, migration: null }, config, cards: [], findingIds: [], requirements: undefined, dashboard: "", canonicalDashboard: "# Kanban board\n", dashboardDrift: false }; }
function checked() { const card = { id: "CARD-0001", title: "New card", status: "backlog", requirements: ["REQ-0001"], grandfathered_requirements: [], acceptance_criteria: [{ id: "AC-0001", text: "Works", requirement: "REQ-0001" }], dependencies: [], replaces: [], replaced_by: [], replacement_reason: null, priority: 1, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z", started_at: null, delivered_at: null, blocked: null, workflow: {}, rework: { design: 0, implementation: 0 }, history: [], why: "Why", notes: "" }; return { kind: "checked", proposal: { requirementChanges: [{ action: "create", temporaryKey: "new", targetRequirement: null, title: "New", body: "Behavior", acceptance: ["Works"], supersedes: [] }], cardChanges: [{ action: "create", temporaryKey: "new-card", targetCard: null, title: "New card", why: "Why", notes: "", requirements: [{ kind: "temporary", key: "new" }], acceptanceCriteria: [{ text: "Works", requirement: { kind: "temporary", key: "new" } }], dependencies: [], priority: 1 }] }, allocation: { requirementIds: { new: "REQ-0001" }, cardIds: { "new-card": "CARD-0001" }, acceptanceIds: { "new-card": ["AC-0001"] }, producerFindingIds: [], checkerFindingIds: [], next: { requirement: 2, card: 2, acceptanceCriterion: 2, finding: 1 } }, impact: { cards: [card], renderedCards: [{ card, why: "Why", notes: "", bytes: "card" }], affectedCardIds: ["CARD-0001"], grandfatheredCardIds: [], designClosures: [] }, producer: { status: "completed", findings: [], summary: "Proposal" }, checker: { status: "pass", criteria: [{ key: "REQ-OBSERVABLE", verdict: "pass", evidence: [] }], findings: [], summary: "Pass" }, artifacts: [{ path: "docs/cards/artifacts/requirements/requirements-producer-KFRUN-20260101T000000000Z-abcdefgh.yaml", bytes: "artifact\n", attestation: { run_id: "KFRUN-20260101T000000000Z-abcdefgh" } }], discovery: { active: [{ name: "requirements-producer", source: "package", path: "agents/requirements-producer.md", sha256: "b".repeat(64) }], ignored: [], unavailable: [] }, models: { producer: { provider: "openai", id: "model", thinking: "medium", inherited: true }, checker: { provider: "openai", id: "model", thinking: "medium", inherited: true } } } as any; }
function bundle(overrides: any = {}) { return prepareRequirementsApproval({ checked: { ...checked(), ...overrides }, snapshot: snapshot(), baseCommit: base, proposedPaths: ["docs/cards/BOARD.md", "docs/cards/CARD-0001.md", "docs/cards/artifacts/requirements/requirements-producer-KFRUN-20260101T000000000Z-abcdefgh.yaml", "docs/cards/board.yaml", "docs/spec.md"], normalization: { roots: { "<REPOSITORY_ROOT>": "/workspace/repo" }, secrets: ["secret-canary"] } }); }

test("renders one canonical complete initial approval document and digest", () => {
  const value = bundle(); assert.match(value.digest, /^sha256:[0-9a-f]{64}$/); assert.match(value.document, /^# Requirements approval\n/); assert.match(value.document, /REQ-0001/); assert.match(value.document, /CARD-0001/); assert.match(value.document, /REQ-OBSERVABLE/); assert.match(value.document, /Active agents and models/); assert.match(value.document, /Authoritative base: a{40}/); assert.ok(value.document.endsWith("\n"));
  assert.doesNotMatch(value.document, /\/workspace\/repo|secret-canary/); assert.deepEqual(value.paths, [...value.paths].sort());
});

test("proposal, base, model, override, artifact, path, and snapshot bits alter the digest", () => {
  const original = bundle().digest;
  const variants = [
    prepareRequirementsApproval({ checked: { ...checked(), proposal: { ...checked().proposal, requirementChanges: [{ ...checked().proposal.requirementChanges[0], title: "Changed" }] } }, snapshot: snapshot(), baseCommit: base, proposedPaths: bundle().paths, normalization: { roots: {} } }),
    prepareRequirementsApproval({ checked: checked(), snapshot: snapshot(), baseCommit: "b".repeat(40), proposedPaths: bundle().paths, normalization: { roots: {} } }),
    bundle({ models: { ...checked().models, checker: { ...checked().models.checker, id: "other" } } }),
    bundle({ discovery: { ...checked().discovery, active: [{ ...checked().discovery.active[0], sha256: "c".repeat(64) }] } }),
    bundle({ artifacts: [{ ...checked().artifacts[0], bytes: "changed\n" }] }),
  ];
  const changedSnapshot = snapshot() as any; changedSnapshot.board.ids.next_finding = 2; variants.push(prepareRequirementsApproval({ checked: checked(), snapshot: changedSnapshot, baseCommit: base, proposedPaths: bundle().paths, normalization: { roots: {} } }));
  for (const variant of variants) assert.notEqual(variant.digest, original);
});

test("requires one explicit decision and refuses dismissal, abort, unsupported mode, and replay", async () => {
  const value = bundle(); const approve = new RequirementsApprovalRequest(value); const accepted = await approve.decide({ request: async ({ digest }) => { assert.equal(digest, value.digest); return "approve"; } }); assert.deepEqual(accepted, { kind: "approved", digest: value.digest }); assertApprovalFresh(accepted, value); await assert.rejects(() => approve.decide({ request: async () => "approve" }), /already been consumed/);
  assert.equal((await new RequirementsApprovalRequest(value).decide({ request: async () => "revise" })).kind, "revision_required"); assert.deepEqual(await new RequirementsApprovalRequest(value).decide({ request: async () => undefined }), { kind: "cancelled", digest: value.digest, reason: "dismissed" }); assert.deepEqual(await new RequirementsApprovalRequest(value).decide(undefined), { kind: "cancelled", digest: value.digest, reason: "unsupported" });
  const controller = new AbortController(); controller.abort(); assert.deepEqual(await new RequirementsApprovalRequest(value).decide({ request: async () => "approve" }, controller.signal), { kind: "cancelled", digest: value.digest, reason: "aborted" }); assert.throws(() => assertApprovalFresh(accepted, bundle({ models: { ...checked().models, checker: { ...checked().models.checker, id: "stale" } } })), /stale/);
});

test("Pi select adapter binds approval to the displayed digest", async () => {
  const selected: any[] = []; const adapter = createPiApprovalAdapter({ select: async (title, options) => { selected.push({ title, options }); return options[0]; } }, true)!; const value = bundle(); assert.equal(await adapter.request(value), "approve"); assert.match(selected[0].title, new RegExp(value.digest)); assert.equal(createPiApprovalAdapter({ select: async () => "Approve" }, false), undefined);
});
