import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { stringify } from "yaml";
import { GitAdapter } from "../../extensions/kanban-flow/state-pr/git.ts";
import { createStateTransactionGit, createStateTransactionRepository, StateTransactionCoordinator } from "../../extensions/kanban-flow/state-pr/transaction.ts";
import type { GitHubAdapter, GitHubPullRequest } from "../../extensions/kanban-flow/state-pr/github.ts";
import { acquireLock, readLockRecord } from "../../extensions/kanban-flow/board/lock.ts";
import { readBoardRepository } from "../../extensions/kanban-flow/board/repository.ts";
import { renderBoard } from "../../extensions/kanban-flow/engine/render.ts";
import { normalizeRequirementsProposal } from "../../extensions/kanban-flow/requirements/proposal.ts";
import { allocateRequirementsProposal } from "../../extensions/kanban-flow/requirements/allocate.ts";
import { planRequirementsImpact } from "../../extensions/kanban-flow/requirements/impact.ts";
import { RequirementsWorkflow } from "../../extensions/kanban-flow/requirements/workflow.ts";
import { buildChildAttestation } from "../../extensions/kanban-flow/agents/attestation.ts";
import { renderArtifact } from "../../extensions/kanban-flow/agents/artifacts.ts";
import { policyForAgent } from "../../extensions/kanban-flow/agents/policy.ts";
import type { DispatchPlan, DispatchSuccess } from "../../extensions/kanban-flow/agents/runner.ts";
import type { ProducerResult, CheckerResult } from "../../extensions/kanban-flow/board/result-schemas.ts";
import { REQUIREMENTS_CRITERIA } from "../../extensions/kanban-flow/requirements/criteria.ts";

const exec = promisify(execFile); const baseTime = "2026-01-01T00:00:00Z";
async function git(cwd: string, ...args: string[]) { return (await exec("git", args, { cwd })).stdout.trim(); }
const config = { repository: { forge: "github", gh_command: "gh", remote: "origin", base_branch: "main" }, state_prs: { merge_policy: "human" }, lock: { ttl_seconds: 1800, heartbeat_seconds: 30 }, scheduler: { wip_limit: 1, priority_order: "ascending" }, rework: { design_limit: 2, implementation_limit: 2 }, review: { lenses: ["acceptance"], max_parallel: 1 }, project_commands: { test: ["npm", "test"] }, agent_models: { default: "inherit", overrides: {} }, agents: { allow_project_overrides: true, report_overrides: true }, resources: { broad_policy_allowed_skills: [] } };
function producer(id: string): ProducerResult { return { schema_version: 1, dispatch_id: id, card_id: "none", phase: "requirements", status: "completed", summary: "Create first requirement", artifacts: [], findings: [], questions: [], evidence: [], planned_paths: [], requirement_changes: [{ temporary_key: "first", action: "create", target_requirement: "none", title: "First behavior", body: "A user can observe the first behavior.", acceptance: ["The first behavior is observable."], supersedes: [] }], card_changes: [{ temporary_key: "first-card", action: "create", target_card: "none", title: "Deliver first behavior", why: "Users need an observable result.", notes: "", requirements: ["first"], acceptance_criteria: [{ text: "The first behavior is observable.", requirement: "first" }], dependencies: [], priority: 1 }] } as ProducerResult; }
function checker(id: string): CheckerResult { return { schema_version: 1, dispatch_id: id, card_id: "none", phase: "requirements", status: "pass", summary: "All criteria pass", criteria: REQUIREMENTS_CRITERIA.map(({ key }) => ({ key, verdict: "pass", evidence: [{ kind: "file", reference: "proposal", summary: "Verified" }] })), findings: [], evidence: [] } as CheckerResult; }
function plan(id: string, role: "requirements-producer" | "requirements-checker", root: string): DispatchPlan { const policy = policyForAgent(role); return { dispatchId: id, agent: { name: role, description: role, body: role, source: "package", path: `agents/${role}.md`, sha256: "d".repeat(64) }, model: { provider: "test", id: "model", thinking: "medium", inherited: true }, policy, executable: "pi", argv: [], redactedArgv: ["--mode", "json"], environment: {}, cwd: root, promptPath: "/tmp/prompt", taskEnvelope: "task", async cleanup() {} }; }
function success(payload: ProducerResult | CheckerResult): DispatchSuccess { return { runtime: { payload, provider: "test", model: "model", thinking: "medium", stopReason: "tool", usage: {}, eventCount: 2 }, exitCode: 0, stderr: "", startedAt: baseTime, completedAt: "2026-01-01T00:00:01Z" }; }
class Github implements GitHubAdapter { created: GitHubPullRequest[] = []; commit = "f".repeat(40); async listPullRequests() { return this.created; } async createPullRequest(input: any) { const pr = { number: 1, url: "https://github.com/owner/repo/pull/1", ...input, state: "open", head_commit: this.commit, merge_commit: null } as GitHubPullRequest; this.created.push(pr); return pr; } async addComment(): Promise<never> { throw new Error("unused"); } async closePullRequest(): Promise<void> { throw new Error("unused"); } async reopenPullRequest(): Promise<void> { throw new Error("unused"); } async getComments(): Promise<never[]> { return []; } }

test("approved initial requirements produce one exact real-Git state PR without changing main", async () => {
  const root = await mkdtemp(join(tmpdir(), "requirements-state-")); const bare = await mkdtemp(join(tmpdir(), "requirements-remote-")); const inspect = await mkdtemp(join(tmpdir(), "requirements-inspect-"));
  try {
    await git(root, "init", "-b", "main"); await git(root, "config", "user.email", "test@example.invalid"); await git(root, "config", "user.name", "Kanban Test"); await mkdir(join(root, "docs/cards"), { recursive: true });
    const board = { harness: "pi", board_schema_version: 1, last_writer_package_version: "1.0.0", project: { repository_id: "owner/repo" }, ids: { next_requirement: 1, next_card: 1, next_acceptance_criterion: 1, next_finding: 1 }, state: { last_reconciled_at: baseTime, last_state_transaction: null }, migration: null };
    await writeFile(join(root, "docs/cards/board.yaml"), stringify(board)); await writeFile(join(root, "docs/cards/config.yaml"), stringify(config)); await writeFile(join(root, "docs/cards/BOARD.md"), renderBoard([])); await git(root, "add", "docs"); await git(root, "commit", "-m", "initialized board"); await git(bare, "init", "--bare"); await git(root, "remote", "add", "origin", bare); await git(root, "push", "origin", "main"); const mainBefore = await git(root, "rev-parse", "main");
    const adapter = new GitAdapter({ cwd: root }); const transactionGit = createStateTransactionGit(adapter); const github = new Github(); const coordinator = new StateTransactionCoordinator(createStateTransactionRepository(), { ...transactionGit, async commitState(input) { github.commit = await transactionGit.commitState(input); return github.commit; } }, github, () => new Date(baseTime));
    const dispatch = { run: async (input: any) => { const producerId = "KFRUN-20260101T000000000Z-abcdefgh"; const checkerId = "KFRUN-20260101T000000000Z-bcdefghj"; const producerPayload = producer(producerId); const checkerPayload = checker(checkerId); const proposal = normalizeRequirementsProposal(producerPayload, input.snapshot); const allocation = allocateRequirementsProposal(input.snapshot, proposal); const impact = planRequirementsImpact(input.snapshot, proposal, allocation, { at: input.plannedAt, operationId: input.operationId, transactionId: input.transactionId, historyIds: { "first-card": "KFH-20260101T000000000Z-cdefghjk" } }); const normalization = { roots: { "<REPOSITORY_ROOT>": root } }; const producerAttestation = buildChildAttestation(plan(producerId, "requirements-producer", root), success(producerPayload), { kind: "parent", repository_id: "owner/repo", branch: null, commit: input.baseCommit, snapshotCommit: null }, normalization); const checkerAttestation = buildChildAttestation(plan(checkerId, "requirements-checker", root), success(checkerPayload), { kind: "immutable_snapshot", repository_id: "owner/repo", branch: null, commit: input.baseCommit, snapshotCommit: input.baseCommit }, normalization); const artifacts = [producerAttestation, checkerAttestation].map((value) => ({ ...renderArtifact(value), attestation: value })); return { kind: "checked", proposal, allocation, impact, producer: producerPayload, checker: checkerPayload, artifacts, discovery: { active: [], ignored: [], unavailable: [] }, models: { producer: { provider: "test", id: "model", thinking: "medium", inherited: true }, checker: { provider: "test", id: "model", thinking: "medium", inherited: true } } }; } };
    const workflow = new RequirementsWorkflow({ acquireLock: ({ operationId }) => acquireLock({ cwd: root, repositoryId: "owner/repo", operationId, command: "requirements", ttlSeconds: 1800 }), preflight: async () => { await adapter.fetch("origin", root); return { kind: "ready", baseCommit: await adapter.resolveRef("origin/main", root), snapshot: await readBoardRepository(root), managedState: [] }; }, dispatch: dispatch as any, approvalAdapter: { request: async () => "approve" }, interactive: true, normalization: { roots: { "<REPOSITORY_ROOT>": root } }, revalidate: async ({ bundle }) => bundle, closeDesign: async () => {}, transaction: coordinator, now: () => new Date(baseTime) });
    const outcome = await workflow.run({ root, repositoryId: "owner/repo", packageVersion: "1.2.3", brief: "Create the first observable behavior", parentModel: { provider: "test", id: "model", thinking: "medium" } }); assert.equal(outcome.status, "proposed", JSON.stringify(outcome)); assert.equal(github.created.length, 1); assert.equal(await git(root, "rev-parse", "main"), mainBefore);
    await git(root, "worktree", "add", "--detach", inspect, github.created[0].head); const proposed = await readBoardRepository(inspect); assert.equal(proposed.requirements?.includes("REQ-0001"), true); assert.deepEqual(proposed.cards.map(({ id }) => id), ["CARD-0001"]); assert.deepEqual(proposed.board.ids, { next_requirement: 2, next_card: 2, next_acceptance_criterion: 2, next_finding: 1 }); assert.equal(proposed.board.state.last_state_transaction?.id, outcome.transactionId); assert.equal(await readLockRecord({ cwd: root, repositoryId: "owner/repo", ttlSeconds: 1800 }), null);
  } finally { await rm(inspect, { recursive: true, force: true }); await rm(root, { recursive: true, force: true }); await rm(bare, { recursive: true, force: true }); }
});
